name: Run Tests

on:
  push:
    branches: [main, pmr]
  pull_request:
    branches: [main, pmr]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage rich pytest pyyaml

      - name: Run unittests
        run: |
          coverage run --source=llmrag -m unittest discover -s tests
          coverage report -m